import Foundation

/// Top-level model representing a full codebase analysis spec.
/// Parsed from YAML output generated by an AI agent's analysis.
struct CodeSpec: Codable, Identifiable, Hashable {
    /// Unique identifier derived from the name
    var id: String { name }

    /// Name of the analyzed project
    let name: String

    /// Spec format version
    let version: Int

    /// Timestamp when the analysis was performed
    let analyzedAt: Date?

    /// Layer definitions that group nodes
    let layers: [SpecLayer]

    /// All nodes (modules, services, components) in the graph
    let nodes: [SpecNode]

    /// All edges (data flows) connecting nodes
    let edges: [SpecEdge]

    /// Entry points into the system (HTTP endpoints, CLI commands, etc.)
    let entryPoints: [EntryPoint]?

    enum CodingKeys: String, CodingKey {
        case name
        case version
        case analyzedAt = "analyzed_at"
        case layers
        case nodes
        case edges
        case entryPoints = "entry_points"
    }
}
