import Foundation

/// Top-level model representing a full codebase analysis spec.
/// Parsed from YAML output generated by an AI agent's analysis.
public struct CodeSpec: Codable, Identifiable, Hashable {
    /// Unique identifier derived from the name
    public var id: String { name }

    /// Name of the analyzed project
    public let name: String

    /// Spec format version
    public let version: Int

    /// Timestamp when the analysis was performed
    public let analyzedAt: Date?

    /// Git SHA for the analyzed repository state.
    public let commitSHA: String?

    /// Additional project-level metadata used by later analysis and sync flows.
    public let metadata: SpecMetadata?

    /// Layer definitions that group nodes
    public let layers: [SpecLayer]

    /// All nodes (modules, services, components) in the graph
    public let nodes: [SpecNode]

    /// All edges (data flows) connecting nodes
    public let edges: [SpecEdge]

    /// Entry points into the system (HTTP endpoints, CLI commands, etc.)
    public let entryPoints: [EntryPoint]?

    /// Named, ordered walkthroughs through the graph.
    public let flows: [SpecFlow]?

    /// Data types referenced by nodes, edges, or flows.
    public let types: [SpecTypeDefinition]?

    enum CodingKeys: String, CodingKey {
        case name
        case version
        case analyzedAt = "analyzed_at"
        case commitSHA = "commit_sha"
        case metadata
        case layers
        case nodes
        case edges
        case entryPoints = "entry_points"
        case flows
        case types
    }
}

public struct SpecMetadata: Codable, Hashable {
    public let repository: String?
    public let language: String?
    public let framework: String?
    public let description: String?
}
